It works. It finally works.
It isn't ready for merge yet, but it finally builds.

diff --git a/ksh93/PKGBUILD b/ksh93/PKGBUILD
--- a/ksh93/PKGBUILD
+++ b/ksh93/PKGBUILD
@@ -1,5 +1,5 @@
-# Note: You may run into issues with for() because of ASLR on windows 10/11
 # TODO: Add patches from the gisburn repo (Such as the ksh93 config), red hat, and debian.
+#
 #
 #
 pkgname=ksh93
@@ -17,14 +17,18 @@ makedepends=(
 source=("${pkgname}-${pkgver}.zip"::https://github.com/ksh93/ksh/archive/refs/tags/v1.0.10.zip)
 sha256sums=('ab412118ce9527c6d805335080593fa874a0b859e9229c172f3fcf55d26f92e9')
 
+# This is necessary
+export PATH="/bin:/usr/bin:$gccdir:$gccdir/include:/usr/include"
+
 # Things might get a bit messary, prepare yourselves.
+# I really should use gisburn's kshrc default config.
 build() {
 	cd "${srcdir}/ksh-${pkgver}"
+	
+	export CYGWIN_CHOST="${CHOST/-msys/-cygwin}"
 
-	local CYGWIN_CHOST="${CHOST/-msys/-cygwin}"
-
-	# Clean up the arch subdir
-	rm -rf ./arch
+	# Do not, I repeat, DO NOT delete the src subdir.
+	# For now, multiple rounds must be done.
 
 	# Bit of a workaround with cc1.exe not found for some reason.
 	export gccdir="/usr/lib/gcc/x86_64-pc-msys/13.3.0"
@@ -37,12 +41,45 @@ build() {
 	export LIBRARY_PATH="/usr/lib/gcc/x86_64-pc-msys/13.3.0"
 
 	export PATH="$PATH:$PWD/arch/msys.i386/lib/probe/C/make"
-	
+
 	# What the inane build system does by default is
 	# entirely a shell script system. It sets 'chmod +x' to the script
 	# but that does nothing with windows. Need to append
 	# shebang at the start.
 	sed -i '1s/^/#!\/usr\/bin\/bash\n/' src/cmd/INIT/mamprobe.sh
 
-	CC="/usr/bin/gcc" /usr/bin/bash bin/package make PACKAGEROOT="$PWD"
+	# It WILL fail during the first round. It MUST be ran twice.
+	printf "This WILL show an error at some point. This is to be expected.\n"
+	printf "The build command is ran twice because of fork() issue.\n"
+	printf "\n\nRound 1 begins now.\n\n"
+	sleep 2
+
+	CC="/usr/bin/gcc" /usr/bin/bash bin/package make PACKAGEROOT="$PWD" || true
+
+	printf "\n\nSecond and final round begins now.\n\n"
+	sleep 2
+	CC="/usr/bin/gcc" /usr/bin/bash bin/package make PACKAGEROOT="$PWD" || true
+
+	sleep 2
+	printf "\n\nFinished!\n\n"
+	sleep 2
+
+
+}
+
+package() {
+	cd "${srcdir}"
+	install -dm0755 "${pkgdir}/etc/skel"
+	install -dm0755 "${pkgdir}/usr/share/ksh"
+	install -dm0755 "${pkgdir}/usr/share/doc/ksh"
+	install -dm0755 "${pkgdir}/usr/share/licenses/ksh"
+
+	# Install the core components of ksh93
+	cd "${srcdir}/ksh-${pkgver}"
+	CC="/usr/bin/gcc" /usr/bin/bash bin/package install "${pkgdir}/usr" PACKAGEROOT="$PWD"
+
+	# install ksh sample rc file
+
+	# Install copyright and license files
+	# Other stuff
 }
