pacman: Update to 5.2.1

diff --git a/pacman/0100-contrib.patch b/pacman/0100-contrib.patch
--- a/pacman/0100-contrib.patch
+++ b/pacman/0100-contrib.patch
@@ -13,8 +13,8 @@ diff -Naur pacman-contrib-1.0.0-orig/src/checkupdates.sh.in pacman-contrib-1.0.0
 --- pacman-contrib-1.0.0-orig/src/checkupdates.sh.in	2015-10-18 08:38:28.000000000 +0300
 +++ pacman-contrib-1.0.0/src/checkupdates.sh.in	2016-07-15 09:42:18.779037400 +0300
 @@ -35,11 +35,6 @@
- 	exit 0
- fi
+ 	shift
+ done
  
 -if ! type -P fakeroot >/dev/null; then
 -	error 'Cannot find the fakeroot binary.'
@@ -30,8 +30,8 @@ diff -Naur pacman-contrib-1.0.0-orig/src/checkupdates.sh.in pacman-contrib-1.0.0
  ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
 -if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
 +if ! pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
-        error 'Cannot fetch updates'
-        exit 1
+ 	error 'Cannot fetch updates'
+ 	exit 1
  fi
 diff -Naur pacman-contrib-1.0.0-orig/src/paccache.sh.in pacman-contrib-1.0.0/src/paccache.sh.in
 --- pacman-contrib-1.0.0-orig/src/paccache.sh.in	2015-03-26 07:43:10.000000000 +0300
@@ -42,9 +42,9 @@ diff -Naur pacman-contrib-1.0.0-orig/src/paccache.sh.in pacman-contrib-1.0.0/src
  declare -a cachedirs=() candidates=() cmdopts=() whitelist=() blacklist=()
 -declare -i delete=0 dryrun=0 filecount=0 move=0 needsroot=0 totalsaved=0 verbose=0
 +declare -i delete=0 dryrun=0 filecount=0 move=0 totalsaved=0 verbose=0
+ declare -i min_atime=0 min_mtime=0
  declare    delim=$'\n' keep=3 movedir= scanarch=
  
- QUIET=0
 @@ -123,16 +123,7 @@
  m4_include(../scripts/library/size_to_human.sh)
  
@@ -81,18 +81,6 @@ diff -Naur pacman-contrib-1.0.0-orig/src/paccache.sh.in pacman-contrib-1.0.0/src
  	# unlikely that this will fail, but better make sure
  	pushd "$cachedir" &>/dev/null || die "failed to chdir to '%s'" "$cachedir"
  
-diff -Naur pacman-contrib-1.0.0-orig/src/paclist.sh.in pacman-contrib-1.0.0/src/paclist.sh.in
---- pacman-contrib-1.0.0-orig/src/paclist.sh.in	2014-12-24 04:16:59.000000000 +0300
-+++ pacman-contrib-1.0.0/src/paclist.sh.in	2016-07-15 09:42:18.796037400 +0300
-@@ -59,7 +59,7 @@
- 	exit 0
- fi
- 
--printf -v installed '[%s]' "$(gettext installed)"
-+printf -v installed '[%s]' "$(/usr/bin/gettext installed)"
- pacman -Sl $1 | awk -v i="$installed" '$NF == i { print $2,$3 }'
- 
- # exit with pacman's return value, not awk's
 diff -Naur pacman-contrib-1.0.0-orig/src/pacscripts.sh.in pacman-contrib-1.0.0/src/pacscripts.sh.in
 --- pacman-contrib-1.0.0-orig/src/pacscripts.sh.in	2016-01-04 06:27:45.000000000 +0300
 +++ pacman-contrib-1.0.0/src/pacscripts.sh.in	2016-07-15 09:42:18.804037400 +0300
