heimdal: work around parallel build problems
Turns out that heimdal does not build all that easily when passing
`MAKEFLAGS=-j15`...

Let's do what we would do interactively: simply try again, up to four
times. That should do it.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/heimdal/PKGBUILD b/heimdal/PKGBUILD
--- a/heimdal/PKGBUILD
+++ b/heimdal/PKGBUILD
@@ -61,7 +61,16 @@ build() {
     --disable-ndbm-db \
     --disable-heimdal-documentation
   
-  make LDFLAGS="${LDFLAGS} -no-undefined"
+  counter=0
+  while ! make LDFLAGS="${LDFLAGS} -no-undefined"
+  do
+    counter=$(($counter+1))
+    test $counter -lt 5 || {
+      echo "Could not build (tried 5 times)" >&2
+      exit 1
+    }
+  done
+
   setup
 }
 
