pacman-contrib: Update to 1.10.1
simple patch refresh

diff --git a/pacman-contrib/0100-contrib.patch b/pacman-contrib/0100-contrib.patch
--- a/pacman-contrib/0100-contrib.patch
+++ b/pacman-contrib/0100-contrib.patch
@@ -20,9 +20,9 @@
  edit = sed \
  	-e 's|@bindir[@]|${bindir}|g' \
  	-e 's|@sysconfdir[@]|$(sysconfdir)|g' \
---- pacman-contrib-v1.5.1/src/checkupdates.sh.in.orig	2022-05-06 22:27:02.828090100 +0200
-+++ pacman-contrib-v1.5.1/src/checkupdates.sh.in	2022-05-06 22:27:39.442955500 +0200
-@@ -101,10 +101,6 @@
+--- pacman-contrib-v1.10.1/src/checkupdates.sh.in.orig	2024-01-04 03:28:56.000000000 +0100
++++ pacman-contrib-v1.10.1/src/checkupdates.sh.in	2024-01-05 12:15:22.106799900 +0100
+@@ -120,10 +120,6 @@
  	unset ALL_OFF BOLD BLUE GREEN RED YELLOW
  fi
  
@@ -33,13 +33,13 @@
  if [[ -z $CHECKUPDATES_DB ]]; then
  	CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-${UID}/"
  fi
-@@ -119,7 +115,7 @@
- if (( ${SYNC} )); then
+@@ -142,7 +138,7 @@
+ if (( SYNC )); then
  	mkdir -p "$CHECKUPDATES_DB"
  	ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
 -	if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
 +	if ! pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
- 	    die 'Cannot fetch updates'
+ 		die 'Cannot fetch updates'
  	fi
  fi
 --- pacman-contrib-v1.5.1/src/paccache.sh.in.orig	2022-05-04 07:27:40.000000000 +0200
@@ -89,18 +89,18 @@
  	# unlikely that this will fail, but better make sure
  	pushd "$cachedir" &>/dev/null || die "failed to chdir to '%s'" "$cachedir"
  
---- pacman-contrib-v1.5.1/src/pacscripts.sh.in.orig	2022-05-04 07:27:40.000000000 +0200
-+++ pacman-contrib-v1.5.1/src/pacscripts.sh.in	2022-05-06 22:31:24.676027200 +0200
+--- pacman-contrib-v1.10.1/src/pacscripts.sh.in.orig	2024-01-04 03:28:56.000000000 +0100
++++ pacman-contrib-v1.10.1/src/pacscripts.sh.in	2024-01-05 12:13:48.814196300 +0100
 @@ -29,7 +29,7 @@
  
  error() {
  	local mesg=$1; shift
--	printf "==> $(gettext "ERROR:") ${mesg}\n" "$@" >&2
-+	printf "==> $(/usr/bin/gettext "ERROR:") ${mesg}\n" "$@" >&2
+-	printf "==> $(gettext "ERROR:") %s\n ${mesg}" "$@" >&2
++	printf "==> $(/usr/bin/gettext "ERROR:") %s\n ${mesg}" "$@" >&2
  }
  
  usage() {
-@@ -61,17 +61,7 @@
+@@ -63,17 +63,7 @@
  }
  
  spacman() {
@@ -119,7 +119,7 @@
  }
  
  print_db() {
-@@ -88,7 +78,7 @@
+@@ -92,7 +82,7 @@
  }
  
  print_pkg() {
@@ -128,7 +128,7 @@
  		error "Package $1 does not include any .INSTALL script"
  		return 1
  	fi
-@@ -97,7 +87,7 @@
+@@ -101,7 +91,7 @@
  
  print_scriptlet() {
  	if [ -f "$1" ]; then
